### ISSUE TITLE
[DESIGN] Stamina bar

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1012]
## 🎨 Design
In reference to #985, this bar represents the stack of available 'charges' for the basic skill.
### Specifications:
- It should be positioned below the player health bar.
- Clearly indicate each charge within the bar.
- Utilize a distinct color to represent the 'loading' charge state.
- Provide visual feedback when the player attempts to use the basic skill, but no charges are left."

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1kzVlYVbjLmj1B44ft2zK4cd41yDMeTj3?usp=drive_link assets + references

**Comment by jazimp** [comment]
_Reference_:
The first basic is loaded.
The second basic is loading.
The third basic is not loaded. 

_Reference-0_:
The three basics are loaded.

_Reference-1_:
The three basic are not loaded.

_Reference-2_:
Visual feedback for the player when attempting to use the basic without available load.

**Comment by jazimp** [comment]
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/68ba83b9-0eb6-4aea-a453-92ff90c63971)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/57125460-b9c4-4740-a391-32e89dedfa44)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/3867fcf2-e2c8-4f40-ad19-43a2dbdd6b93)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/690c7dca-c8d3-4b2b-89e3-001e06028f82)

**Comment by jazimp** [comment]
**Note**: In the references provided, there is an update regarding the health bar. The assets and reference for that update can be located here: https://drive.google.com/drive/folders/1VcuHIjD7k6mJV7XzSZvog7LRUPGHEQdh?usp=drive_link
