### ISSUE TITLE
[FEATURE] Settings screen (main menu and in game)

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1013]
## 🚀 Feature
The settings menu can be accessed from the main menu. It includes the following sections:
#### Sound Section:
- Toggle for muting/unmuting music.
- Music volume slider.
- Toggle for muting/unmuting sound effects (SFX).
- SFX volume slider.
#### Account Section:
- Sign in: Link your account using OAuth.
- Sign out (if already logged in).

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1icjh-wXViUbYebV7ixZ78CzZxH2dPVl6?usp=drive_link assets + reference (audio/account)

**Comment by jazimp** [comment]
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/2226120e-49d7-45d4-a1ce-d29d6cbcceec)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/3adb2f4a-ebf2-49f9-9658-b7a3012bf340)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/1cabc2f7-5d5e-4130-b9d8-5a8028d0d75e)

**Comment by jazimp** [comment]
Assets

https://drive.google.com/drive/folders/1icjh-wXViUbYebV7ixZ78CzZxH2dPVl6?usp=drive_link 

Reference

![reference](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/2af24835-3a2c-45b8-9199-08ec88a4496b)
