### ISSUE TITLE
[DESIGN] Preparing battle UI

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1046]

**Comment by jazimp** [comment]
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/8b5944b3-8954-463b-b53f-b55373dc6fb3)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/f1a6bf72-caed-47f3-beef-2e87881f4c28)

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1ra-sO0G9YwVHueII5B7PgJm8Xqcua6xz?usp=drive_link assets + references

**Comment by jazimp** [comment]
![reference - screen 1](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/4978d416-bff2-4c52-b9e9-689fb7dbf47e)
![reference - screen 2](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/cac05a47-fab7-48cd-bb39-87066bf4caa8)
![reference - screen 3](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/a45813aa-4684-437e-bf3c-15a24b94ae9c)

**Comment by jazimp** [comment]
![reference - screen 1](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/49e13c97-20c5-4378-aea5-37e832ed302e)
![reference - screen 2](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/1b9f5339-84cd-4aba-bf17-11564d39fb75)
![reference - screen 3](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/3538d3a3-a92c-4b71-84f9-64067d5a32b2)
