### ISSUE TITLE
[DESIGN] Winner/Defeated message

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1079]
## 🎨 Design
Design a winner/defeated message popup that activates when a player either wins or loses a match. This popup will be displayed on the screen immediately upon victory or defeat and will remain visible until the winner/defeated overlay is shown. 

The goal is to create a visually engaging and informative message that enhances the player's experience while seamlessly transitioning to the next phase of the game.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1oiXgfnLxjISlzJb8aPw60BA77sYaSNGV?usp=drive_link in this folder are the assets for the visual feedback when the player is killed

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1sXvQomDqcO2NwPdhtzq6U_7qglZkGmWP?usp=drive_link assets + reference: win/defeat screen
