### ISSUE TITLE
[FEATURE] Metrics/info display relocation

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1109]
## 🚀 Feature
Relocate the FPS, ping, and server/client hashes to a different position, primarily to prevent overlap with the iPhone's status bar.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1lJmqn_wjMwGpbYma9nOXuzmZjTUXaN_k?usp=drive_link assets + reference 

![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/ce515a7b-43c2-4e6a-bb21-283820507934)
