### ISSUE TITLE
[FEATURE] Update buttons

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1205]
## 🚀 Feature
Update the buttons following the design references.

1. Title: secondary button.
2. Main: primary button (large).
3. Character info: primary button.
4. Lobby: secondary button (small).

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1h93h0kjVentkQGeoLqCXmc7HB0Y7pBGr?usp=drive_link assets + guide



![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/54f18aa3-cb12-48b4-9952-ec29aae5e2eb)
