### ISSUE TITLE
[FEATURE] Title screen improvements

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1206]
## 🚀 Feature
1. Change VERSION: XXX to "pre-alpha".
2. Remove the "Change Name" button (it will be in the main screen settings menu).
3. Set a default player name and avatar.
4. Move "Lambda SAS..." up so the iOS bar doesn't cover it.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/165tfI_iMt8CDIrw7Ji12JIAspm1JbnpR?usp=drive_link reference + assets

**Comment by AngieDutra** [comment]
I implemented this and is currently in main
