### ISSUE TITLE
[FEATURE] Update match state info

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1250]
## 🚀 Feature
Update match state info according to the new design.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1Kz9CvvnH_w4coc0TzVXmxTzm39pFP0VB?usp=drive_link reference + assets

![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/958a4e31-85cf-4e08-a241-df9b53634f1c)
