### ISSUE TITLE
[DESIGN] Update in game UI

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1251]
## 🎨 Design
Update in-game skills buttons according to the new design aesthetics.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1XXidYpdzqBsO0mFP5GGpZiMHwswiLvYc?usp=drive_link references + assets

**Comment by jazimp** [comment]
Game started:
![Image](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/d3c054c0-f13e-4033-a097-eba6960741af)


Super skill and item disabled:
![Image](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/9a24e2d0-02de-4307-a3fa-9da1f2d5e617)

Drag of the super:
![Image](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/f88e127c-21e7-4874-84e4-cbb0390e7395)

Drag of the basic + drag of the joystick:
![Image](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/13d7bceb-4fdf-4463-a60f-a5b4600eecb1)

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1XXidYpdzqBsO0mFP5GGpZiMHwswiLvYc?usp=drive_link assets + references

**Comment by jazimp** [comment]
![reference](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/3aa9ffd5-266e-443a-811a-966859f68e49)

**Comment by jazimp** [comment]
![reference 1](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/cc8416b7-bc5d-4905-b04a-783170aaffdb)

**Comment by AngieDutra** [comment]
Done!
