### ISSUE TITLE
[DESIGN] Update Searching/Found Lobby screens 

### ISSUE THREAD

**Issue by jazimp** [lambdaclass/curse_of_mirra#1282]
🎨 Design
Searching and found lobby screens design update. 

Changes:
1. Background
2. Typographic variables

New:
1. Icon/Coin 3d

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1TsIHq3p5g6XHnp-lTzYfDjQ5au3i5Oa7?usp=drive_link assets

**Comment by jazimp** [comment]
![screen 1](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/ba94d836-2224-49ee-bf6d-98a2468a213e)
![screen 2](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/598b4a87-c5f3-4fb5-a41f-de13090d94cc)
![screen 3](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/bf85a90b-741e-48c1-bfe9-11321508596b)

**Comment by AngieDutra** [comment]
Outdated but done
