### ISSUE TITLE
[FEATURE] Re implement player name

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1303]
## 🚀 Feature
Related: https://github.com/lambdaclass/curse_of_mirra/pull/1040

- Until we have a centralized player database, each server will have its own.
- If the player tries to connect to a server and they have not created a user or haven't set a name before, it should prompt for name input before continuing to the MainScene.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1mucbA03nZXnmvBQCYUXsSyVaMSnEzL_6?usp=drive_link assets 

![reference](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/3a9ab14e-1e60-40d7-9b78-4f49588a9e95)
