### ISSUE TITLE
[DESIGN] Character selection flow

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1351]
## 🎨 Design

The current screen flow between character info and main screen is a bit confusing due to buttons position and backgrounds.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1koTdE5RICL81YsMDn9zVMKpYhl0vC1Ax?usp=drive_link assets + reference (the background is a placeholder)

**Comment by jazimp** [comment]
![reference](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/5235d192-6c53-4451-a0ee-52ce61f9a738)

**Comment by AngieDutra** [comment]
Done
