### ISSUE TITLE
[BUG] Fix info on death splash screen

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_mirra#1359]
## 🐛 Bug Report

This is a bug on the main branch backend.

- model missing
- rank missing
- kills
- check for other issues

**Comment by BertovDev** [comment]
- [ ]     model missing
- [ ]     rank missing
- [ ]     kills 
- [ ]     check for other issues


There is no Killfeed events in the backend so Kills can not be showed.
