### ISSUE TITLE
[BUG] Restore killfeed

### ISSUE THREAD

**Issue by AngieDutra** [lambdaclass/curse_of_mirra#1372]
## 🐛 Bug Report

The killfeed does not show in game or in end game splash

The zone icon shows even if a player kills you
<img width="140" alt="Captura de pantalla 2024-01-30 a la(s) 10 25 43" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/c474c9b4-e90c-40ae-b8fe-d01c3430c82f">

**Comment by BertovDev** [comment]
Entity.Player.Killcount is always set to 0 in the backend.
