### ISSUE TITLE
[DESIGN] Re-Design Orientation Circle and Arrow

### ISSUE THREAD

**Issue by BertovDev** [lambdaclass/curse_of_mirra#1429]
## 🎨 Design

_**The problem:**_
Now we have the orientation circle and arrow separated in two. With the implementation of new stamina system this is a problem. Becuase the stamina indicators end up so far from the circle.

<img width="242" alt="Screenshot 2024-02-14 at 12 31 00" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/6765d5fc-3605-4853-b41c-e6639c5b6eba">
<img width="242" alt="Screenshot 2024-02-14 at 12 31 05" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/05800a01-5513-4c67-a128-e724dbd28e1d">

_**The fix:**_
Combinate both indicators Orientation Circle and Arrow into one. Like this reference
<img width="360" alt="Screenshot 2024-02-14 at 12 21 27" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/13d314c3-557f-4f9c-b0d3-8dfef2e316e8">

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/14uuebCawVLVZsi5mV0WiCqr5kGoyHY_B?usp=drive_link assets + reference for stamina and direction indicator

**Comment by AngieDutra** [comment]
Done!
