### ISSUE TITLE
[BUG] Fix differences in Character Info

### ISSUE THREAD

**Issue by jazimp** [lambdaclass/curse_of_mirra#1433]
## 🐛 Bug Report
The following modifications need to be made in the implementation of Character Info, using the image as reference:

1. Add the title of the screen.
2. Adjust the spacing between the character's name and the short brief description.
3. Increase the text size of the character's short brief description.
4. Add shadows to the "soon" text of the buttons.
5. The selected state of the skills needs to be thinner.
6. Replace "skill1", "skill2", and "skill3" with their correct names (check notion page).

#### Reference 
![new](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/07144a1b-0790-4337-b830-92efd96bfb1a)

**Comment by BertovDev** [comment]
Current state after changes:

<img width="798" alt="Screenshot 2024-02-15 at 10 08 56" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/07d253b2-aee1-469c-a78f-6f4d55a0c286">

**Comment by BertovDev** [comment]
- [ ]     Add the title of the screen.
- [ ]     Adjust the spacing between the character's name and the short brief description.
- [ ]     Increase the text size of the character's short brief description.
- [ ]     Add shadows to the "soon" text of the buttons.
- [ ]     The selected state of the skills needs to be thinner.
- [ ]     Replace "skill1", "skill2", and "skill3" with their correct names (check notion page).

**Comment by BertovDev** [comment]
<img width="840" alt="Screenshot 2024-02-15 at 11 20 02" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/cfebac1a-2115-4faa-b0af-ea5fe3fa8f7b">

**Comment by BertovDev** [comment]
Last update

<img width="840" alt="Screenshot 2024-02-15 at 11 29 10" src="https://github.com/lambdaclass/curse_of_mirra/assets/62818001/31745bdf-d4a9-499e-85b4-ec01a171df13">
