### ISSUE TITLE
[REFACTOR] Survive in prepareforbattle

### ISSUE THREAD

**Issue by BertovDev** [lambdaclass/curse_of_mirra#1511]
## 🚧 Refactor

Update survive animation in prepareforbattle.

**Comment by AngieDutra** [comment]
The current smoke effect could be replaced by a lighter sand-looking effect. The assets to be used could be from the new kill zone effect. This is if that effect is event wanted. In case of a full refactor in the animation maybe with a light overlay animated behind the text this issue could be solved
