### ISSUE TITLE
[FEATURE] Feedback for unavailable stamina

### ISSUE THREAD

**Issue by jazimp** [lambdaclass/curse_of_mirra#1531]
## 🚀 Feature

It's necessary to implement feedback for the scenario where the player wants to use a skill but doesn't have any stamina available.

- Images 3 and 4 work together, with 4 being a transitional state, clearly showing the player that they don't have staminas available to use until the first one has recharged.

- To enhance the feedback, in the implementation, a movement animation accompanied by a red glow can be added.

_Observation_: Image 4 is the feedback for the player when they attempt to use a skill but don't have any stamina available.

### Assets

https://drive.google.com/drive/folders/14uuebCawVLVZsi5mV0WiCqr5kGoyHY_B?usp=drive_link

### Reference

![stamina](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/e1b02f2f-667d-4927-9cf5-d5aef83f7d17)

**Comment by AngieDutra** [comment]
I'll see the possibility of including solution of #1532 here if it's simple to fix
