### ISSUE TITLE
[FEATURE] Dynamic tips on Lobby screen

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_mirra#1724]
## 🚀 Feature
The goal is to enhance the searching lobby screen and make it more dynamic. The changes include:

1. Displaying the selected character portrait.
2. Presenting a random tip.

For this initial iteration, let's utilize a scriptable object for managing the tips.

**Comment by mgrunwaldt** [comment]
We need to create a general pool and a pool per character, and that way when you choose a character it chooses randomly between the general and your pool.

To start, these are the tips we will have for each character

**Muflus**
1. LEAP into your opponents and unleash your fury!
2. CRUSH adversaries with the relentless power of your saw!
3. RAMPAGE into the action as enemies flee in desperation!
4. Outsmart opponents by leaping to unexpected hideouts.
5. Pro tip: Use the MAGIC BOOTS to combine strength and agility.

**H4CK**
1. Use you SLINGSHOT and strike up to 3 enemies at once!
2. Your enemy is hiding behind a wall? No worries, use your Ulti and make it rain!
3. Stuck in a bad place? FLASH out before they catch you!
4. Use your speed and don't let anyone hit you.
5. Pro tip: Take advantage of your slingshot and fight from a safe distance.


**Uma**
1. With three knife stabs, AVENGE your kind!
2. Channel your VEIL OF RADIANCE and vanish into the shadows!
3. SNEAK into opponents when they least expect you!
4. Use well your invisibility: any action you make will bring you back to light.
5. Pro tip: approach a weak opponent while invisible and stab him before he even sees you 


**Valtimer**
1. Release ANTIMATTER and blast your enemies!
2. Spawn a black hole and trap your enemies!
3. Open a portal and WARP away!
4. Teleport through a wall and leave your opponents hanging
5. Pro tip: Aim your ANTIMATTER into a black hole you spawned and unleash it's full strength

**And for general tips:**
1. Low on health? Disengage from the battle and you'll see how you recover over time
2. Don't chicken out: if you don't get power ups it will be really hard to win the match
3. Break them crates and get stronger and stronger!
4. Use the items well: they can make a difference between victory and defeat
5. Don't let the sandstorm get you!
6. Use Magic Boots to run faster than the rest!
7. Use Myrra's Blessing and become inmune to all damage!
8. Use Golden Clock to charge your ulti and reset all cooldowns!
