### ISSUE TITLE
Unity performance

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/curse_of_mirra#470]
The main goal is to improve the game performance. To do that, we first need to collect some metrics and once we know where the pain points are, we can plan how to address the improvements.

#### We need to measure the impact of:
- Scripts
- Assets size/compression.
- Models
- Visual effects
- Shaders

#### Output
- The results need to include a maximum boundary for the weight of 3D assets, measured in poly count. Context: 3d modelers need to know the maximum poly count they are allowed to use for each character. Therefore, we need to estimate the maximum poly count we can handle and then estimate how much we will use for the complete map and for each of the 20 characters in the match.

**Comment by ncontinanza** [comment]
Some useful resources I found while researching this topic:

- [Unity's basic tutorial](https://learn.unity.com/tutorial/profiling-applications-made-with-unity#5c7f8528edbc2a002053b5b6), useful to get an introduction to the existing profiling tools and get some links to dive deeper.
- A more practical [video](https://www.youtube.com/watch?v=uXRURWwabF4), with some good examples and demos
- The Unity profiler's [docs](https://docs.unity3d.com/Manual/Profiler.html?utm_source=demand-gen&utm_medium=pdf&utm_campaign=asset-links-gmg-choose-unity-for-multiplatform&utm_content=optimize-game-performance-2020-lts-ebook).
- Unity's [tutorial](https://learn.unity.com/tutorial/diagnosing-performance-problems-2019-3?language=en#) about the profiler window.
- [Some tips](https://unity.com/how-to/advanced-programming-and-code-architecture) to improve performance in a Unity project.
- [Memory profiler manual](https://docs.unity3d.com/Packages/com.unity.memoryprofiler@0.1/manual/index.html) (not the same as the profiler)
- A [video](https://www.youtube.com/watch?v=6Ra3ouahAzM) about performance in mobile games.

**Comment by martinacantaro** [comment]
@BertovDev I added more details to the Output section, please let me know if you have any questions!

**Comment by BertovDev** [comment]
@martinacantaro   I leave some tips and feedback for the 3D assets:

- `Use a single skinned Mesh Renderer:` Unity optimizes animation using visibility culling and bounding volume updates and these optimizations are only activated if you use one Animator and one skinned Mesh Renderer in conjunction.

- `Use as few bones as possible:` The fewer bones you use, the better the performance will be. Ideally, keep the number below thirty for mobile devices

- `Polygon count`: For mobile devices, somewhere between 300 and 1500 polygons per mesh will give good results.You may need to reduce the polygon count per mesh if the game has lots of characters on screen at any given time.

- `Use as few materials as possible`: You should also keep the number of materials on each mesh as low as possible. However, two or three materials per character should be sufficient in almost all cases.
