### ISSUE TITLE
[BUG] - Interpolation and bots

### ISSUE THREAD

**Issue by tvillegas98** [lambdaclass/curse_of_mirra#487]
## 🐛 Bug Report

There's an error that involves interpolation and bots that causes an argument index error, here's the explanation:
Interpolation causes other players (not the one you're playing) to move 100ms in the past, thus,  if a bot counts as another player, in the moment we invoke a new bot, the client tries to render the movement of that bot 100ms in the past and then causing an argument index error, here's a detailed explanation:

Let's suppose the server updates takes 30ms
Player1 is at $T_1=1000ms$: At this moment, only Player1 is in the game.
Player1 sends the message to the server to spawn a bot at $T_2=1050ms$
Player1 receives the message from the server that the server spawned at $T_3=1110ms$
Due to how the interpolation works the Player1's client tries to render the bot's movement at $T_4 = T_3 - 100ms = 1010ms$ but at $T_4$ the bot didn't exist in the game

This game doesn't break the game but causes an error in the console

**Comment by manucamejo** [comment]
Are we going to have bots in the middle of a game? Maybe fixing this isn't a priority.
