### ISSUE TITLE
[FEATURE] Uma

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_mirra#807]
### Avenge (Basic)
- [ ] Melee attack, performs three consecutive stabs with her knife

### Veil of Radiance (Special)
- [ ] Charges her lamp in the air, releasing a circular nova of light that damages enemies

### Sneak (Dash)
- [ ] Uma dashes becoming invisible

**Comment by saugon** [comment]
@marco-paulucci We have some questions:
1. How much time should elapse between each stab?
2. If a target is blinded, can the skill autoaim target uma?
